### ISSUE TITLE
Expand all

### ISSUE THREAD

**Issue by michaelganesan26** [ca77y/angular-ya-treeview#22]
If you have multiple nested layers how do you expand all and collapse all of the nodes? I am setting the collapsed state to true and false, but it is not working! Any suggestions?

**Comment by ca77y** [comment]
you can't just set the value, you need to use expand/collapse on scope. to expand all you can combine expand and onExpand event.

**Comment by michaelganesan26** [comment]
Thank you for the reply. I decide to write my own directive. I needed additional features. Good job with your control!
