### ISSUE TITLE
Question Not Issue: Select Node Dynamically

### ISSUE THREAD

**Issue by zavierrodriguez** [ca77y/angular-ya-treeview#25]
Thanks for the great code.  Trying to come up with a way to select a node programmatically, preferably by name.  Do you an idea on how to accomplish this.  I'm new to AngularJS so any help would be appreciated.  Thanks.

**Comment by ca77y** [comment]
the context has selectedNode, you can just assign a node to it which you want to select. the context also has rootNode which you can use to search for the node you want to select.

**Comment by zavierrodriguez** [comment]
Will this automatically expand the selected node?
