### ISSUE TITLE
Template File inclusion

### ISSUE THREAD

**Issue by manishrw** [ca77y/angular-ya-treeview#28]
We want some changes in the template file.The module without template file (tpls files) require template files to be at dist directory.
templates/ya-treeview/treeview.tpl.html  required at module/dist/

How do we use it, we need to manually change the ya-treeview.js to point it at root level. 
/templates/ya-treeview/treeview.tpl.html

So, while deploying in production (automated), this change needs to be done manually. Could you fix it ? or any other alternate solution.

**Comment by ca77y** [comment]
you just need to preload your templates with the path the treeview expects, you dont have to actually have your templates there. 

```
var myApp = angular.module('myApp', []);
  myApp.run(function($templateCache) {
  $templateCache.put('templateId.html', 'This is the content of the template');
});
```

same as angular ui https://stackoverflow.com/questions/17660947/can-you-override-specific-templates-in-angularui-bootstrap
